schema = 1
id = "gotify"
name = "Gotify"
description = "Send push notifications to your browsers and devices."
category = "Notifications"
image = "gotify/server:3.1.1"
port = 8084
container_port = 80
data_path = "/app/data"
docs = "https://gotify.net/docs/install"
icon = "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/gotify.svg"

[environment]
TZ = "UTC"
GOTIFY_DEFAULTUSER_NAME = "admin"

[[secrets]]
environment = "GOTIFY_DEFAULTUSER_PASS"
bytes = 24

[database]
engines = ["mysql", "mariadb"]
engine = "postgres"

[database.environment]
GOTIFY_DATABASE_DIALECT = "postgres"
GOTIFY_DATABASE_CONNECTION = "${DATABASE_URL}"

[database.engine_environment.mysql]
GOTIFY_DATABASE_DIALECT = "mysql"
GOTIFY_DATABASE_CONNECTION = "${DATABASE_GO_MYSQL_DSN}"

[database.engine_environment.mariadb]
GOTIFY_DATABASE_DIALECT = "mysql"
GOTIFY_DATABASE_CONNECTION = "${DATABASE_GO_MYSQL_DSN}"

[database.engine_ssl_modes]
postgres = ["disable","require","verify-full"]
mysql = ["disable","require","verify-full"]
mariadb = ["disable","require","verify-full"]
