#!/bin/sh
# Install a checksum-verified Selfhost release without a package manager.
set -eu

version=latest
bin_dir=${HOME:?HOME must be set}/.local/bin
force=false
modify_path=true
while [ "$#" -gt 0 ]; do
    case "$1" in
        --version) version=${2:?Missing version}; shift 2 ;;
        --bin-dir) bin_dir=${2:?Missing installation directory}; shift 2 ;;
        --force) force=true; shift ;;
        --no-modify-path) modify_path=false; shift ;;
        --help) printf '%s\n' 'Usage: sh install.sh [--version VERSION] [--bin-dir DIRECTORY] [--no-modify-path] [--force]' 'Rerun to update with a backup. --force reinstalls even when the binary is unchanged.'; exit 0 ;;
        *) printf 'Unknown option: %s\n' "$1" >&2; exit 1 ;;
    esac
done
case "$version" in
    latest) release=latest/download ;;
    *) version=${version#v}
       printf '%s\n' "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || { echo 'Expected a stable version such as 0.1.1.' >&2; exit 1; }
       release=download/v$version ;;
esac
case "$(uname -s)" in
    Linux) platform=linux ;;
    Darwin) platform=darwin ;;
    *) echo 'Use install.ps1 on Windows. Only Linux and macOS are supported by this installer.' >&2; exit 1 ;;
esac
case "$(uname -m)" in
    x86_64|amd64) arch=x64 ;;
    arm64|aarch64) arch=arm64 ;;
    *) echo 'Supported architectures: x64 and ARM64.' >&2; exit 1 ;;
esac
command -v curl >/dev/null || { echo 'curl is required.' >&2; exit 1; }
asset=selfhost-$platform-$arch
base=https://github.com/Obiente/selfhost/releases/$release
mkdir -p "$bin_dir"
bin_dir=$(cd "$bin_dir" && pwd -P)
target=$bin_dir/selfhost
if [ -e "$target" ] || [ -L "$target" ]; then
    [ -f "$target" ] && [ ! -L "$target" ] || { echo 'Refusing to replace a symlink or non-file.' >&2; exit 1; }
fi
stage=$(mktemp -d "$bin_dir/.selfhost-install.XXXXXXXX")
# mktemp created this exact directory under the resolved installation directory.
trap 'rm -f "$stage/binary" "$stage/checksums"; rmdir "$stage"' EXIT HUP INT TERM
curl --proto '=https' --tlsv1.2 -fsSL "$base/BINARY-SHA256SUMS" -o "$stage/checksums"
curl --proto '=https' --tlsv1.2 -fsSL "$base/$asset" -o "$stage/binary"
expected=$(awk -v name="$asset" '$2 == name { print $1 }' "$stage/checksums")
printf '%s\n' "$expected" | grep -Eq '^[a-f0-9]{64}$' || { echo 'Missing or ambiguous release checksum.' >&2; exit 1; }
if command -v sha256sum >/dev/null; then
    actual=$(sha256sum "$stage/binary" | awk '{print $1}')
elif command -v shasum >/dev/null; then
    actual=$(shasum -a 256 "$stage/binary" | awk '{print $1}')
else
    echo 'sha256sum or shasum is required.' >&2; exit 1
fi
[ "$actual" = "$expected" ] || { echo 'Checksum mismatch. Existing installation was not changed.' >&2; exit 1; }
chmod 755 "$stage/binary"
installed_version=$("$stage/binary" --version)
printf '%s\n' "$installed_version" | grep -Eq '^selfhost [0-9]+\.[0-9]+\.[0-9]+$' || { echo 'Downloaded binary did not report a stable Selfhost version.' >&2; exit 1; }
if [ "$version" != latest ]; then
    [ "$installed_version" = "selfhost $version" ] || { echo 'Downloaded binary reports a different version.' >&2; exit 1; }
fi
if [ -f "$target" ] && [ "$force" = false ] && cmp -s "$stage/binary" "$target"; then
    printf '%s is already up to date at %s\n' "$installed_version" "$target"
else
    if [ -e "$target" ] || [ -L "$target" ]; then
        [ -f "$target" ] && [ ! -L "$target" ] || { echo 'Refusing to replace a symlink or non-file.' >&2; exit 1; }
        backup=$target.backup.$(date +%s).$$
        # A hard link retains the current binary before the atomic replacement.
        ln "$target" "$backup"
        printf 'Previous binary kept at %s\n' "$backup"
    fi
    mv -f "$stage/binary" "$target"
    printf 'Installed %s at %s\n' "$installed_version" "$target"
fi

# A piped installer cannot change its parent shell. Persist startup configuration
# for new shells and set PATH for commands in this installer process.
shell_quote() {
    printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}
append_source() {
    profile=$1
    if [ -e "$profile" ] && [ ! -f "$profile" ]; then
        printf 'Could not configure PATH in non-file: %s\n' "$profile" >&2
        return 1
    fi
    if ! grep -Fqx "$source_line" "$profile" 2>/dev/null; then
        printf '\n# Selfhost command-line tools\n%s\n' "$source_line" >> "$profile"
        printf 'Configured PATH in %s\n' "$profile"
    fi
}
if [ "$modify_path" = true ]; then
    env_dir=${XDG_DATA_HOME:-$HOME/.local/share}/selfhost
    mkdir -p "$env_dir"
    env_dir=$(cd "$env_dir" && pwd -P)
    env_file=$env_dir/env
    # Do not follow links when replacing the installer's own generated file.
    [ ! -L "$env_file" ] && { [ ! -e "$env_file" ] || [ -f "$env_file" ]; } || { echo 'Refusing to overwrite a linked or non-file Selfhost environment file.' >&2; exit 1; }
    quoted_bin=$(shell_quote "$bin_dir")
    {
        printf '%s\n' '# Selfhost shell environment. Generated by the installer.'
        printf 'case "${PATH-}:" in\n    %s:*) ;;\n    *) export PATH=%s${PATH:+:"$PATH"} ;;\nesac\n' "$quoted_bin" "$quoted_bin"
    } > "$env_file"
    source_line=". $(shell_quote "$env_file")"
    append_source "$HOME/.profile"
    # Bash reads only the first existing login profile, plus .bashrc for
    # interactive non-login shells. Preserve user content and append once.
    append_source "$HOME/.bashrc"
    for profile in "$HOME/.bash_profile" "$HOME/.bash_login"; do
        if [ -f "$profile" ]; then append_source "$profile"; fi
    done
    user_shell=${SHELL:-}
    user_shell=${user_shell##*/}
    zsh_dir=${ZDOTDIR:-$HOME}
    if [ "$user_shell" = zsh ] || [ -f "$zsh_dir/.zshenv" ] || command -v zsh >/dev/null 2>&1; then
        mkdir -p "$zsh_dir"
        append_source "$zsh_dir/.zshenv"
    fi
    fish_dir=${XDG_CONFIG_HOME:-$HOME/.config}/fish
    if [ "$user_shell" = fish ] || [ -d "$fish_dir" ] || command -v fish >/dev/null 2>&1; then
        mkdir -p "$fish_dir/conf.d"
        fish_env=$fish_dir/conf.d/selfhost.fish
        [ ! -L "$fish_env" ] && { [ ! -e "$fish_env" ] || [ -f "$fish_env" ]; } || { echo 'Refusing to overwrite a linked or non-file Selfhost fish configuration.' >&2; exit 1; }
        # Fish single quotes escape backslashes and apostrophes, unlike POSIX sh.
        fish_bin=$(printf '%s' "$bin_dir" | sed "s/\\\\/\\\\\\\\/g; s/'/\\\\'/g")
        printf "# Selfhost command-line tools\nfish_add_path --path --prepend --move -- '%s'\n" "$fish_bin" > "$fish_env"
    fi
    PATH="$bin_dir${PATH:+:$PATH}"
    export PATH
    printf '%s\n' 'PATH is configured. Open a new terminal to use Selfhost; no manual shell configuration is needed.'
else
    printf 'PATH was not changed. Add %s to PATH or use the full executable path.\n' "$bin_dir"
fi
printf '%s\n' 'Run selfhost --help or selfhost serve. No services were started.'
